name: Publish Image

on:
  workflow_dispatch:
  push:
    paths:
      - app.py
      - config.py
      - requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set date as environment variable
        id: set-date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push image to Docker hub
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            honeok/signalhub:${{ env.DATE }}
            honeok/signalhub:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7